config/routes.rb
ApprenticeDocLab1::Application.routes.draw do
  get "report_bot/unwritten"

  get "report_bot/unchecked"

  get "report_bot/show"

  resources :report_template_entries, :only => [ :edit, :update ]
  
  resources :users

  resources :print_reports, :only => [ :show ]

  resources :templates

  resources :statuses, :only => [ :create, :update, :destroy ]

  resources :sessions, :only => [ :new, :create, :destroy, :show ]

  resources :roles, :only => [ :index, :new, :edit, :create, :update, :destroy ]

  resources :reviews, :only => [ :create, :edit, :update, :destroy ]

  resources :reports, :only => [ :index, :show, :new, :edit, :create, :update, :destroy ] do
    resources :report_entries, :only => [ :new, :edit, :create, :update, :destroy ]
  end

  resources :passwords, :only => [ :new, :create, :show ]

  resources :jobs

  resources :ihks

  resources :codes

  resources :apprenticeships, :only => [ :index, :create, :destroy ]

  root :to => 'sessions#new'

  match '/welcome', :to => 'sessions#show'
  match '/signout', :to => 'sessions#destroy'
  
  

end

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> verhinderte, dass dieses Template gespeichert werden konnte: :</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h1><%= title %></h1>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :maxlength => 200, :size => 20 %>
  </div>

  <%= f.label :job %><br />
  <%= f.collection_select(:job_id, @jobs, :id, :name, :prompt => true) %>
  <br />
  <%= f.label :ihk, 'IHK' %> <br />
  <%= f.collection_select(:ihk_id, @ihks, :id, :name, :prompt => true) %>
  <br />
  <%= f.label :code %> <br />
  <%= f.collection_select(:code_id, @codes, :id, :name, :prompt => true) %>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<%= render 'form' %>

<%= link_to 'Details', @template, :class => 'main' %> |
<%= link_to 'Zurück', templates_path, :class => 'main' %>

app/views/templates/index.html.erb
<h1><%= title %></h1>
<% m = method(:templates_path) %>
<%= pagerViewStart(m) %>
<%= pagerViewPrev(m) %>
<%= pagerViewNext(m) %>
<%= pagerViewEnd(m) %>

<table class="main">
<tr class="main">
<th class="main">Name</th>
</tr>
<% @templates.each do |template| %>
<tr class="main">
<td class="main"><%= template.name %></td>
<td class="main"><%= link_to 'Details', template, :class => 'main' %></td>
<td class="main"><%= link_to 'Bearbeiten', edit_template_path(template), :class => 'main' %></td>
<td class="main"><%= link_to 'Löschen', template, :confirm => 'Sind Sie sicher?', :method => :delete, :class => 'main' %></td>
</tr>
<% end %>
</table>
<br />

<%= link_to 'Neue Template', new_template_path, :class => 'main' %>

app/views/templates/new.html.erb
<%= render 'form' %>

<%= link_to 'Zurück', templates_path, :class => 'main' %>

app/views/templates/show.html.erb
<h1><%= title %></h1>
<p>
  <b>Name:</b>
  <%= @template.name %>
  <br />
  <b>IHK:</b>
  <%= @template.ihk.name %>
  <br />
  <b>Job:</b>
  <%= @template.job.name %>
  <br />
  <b>Code:</b>
  <br />
  <%=raw @template.code.code %>
  <br />
</p>


<%= link_to 'Bearbeiten', edit_template_path(@template), :class => 'main' %> |
<%= link_to 'Zurück', templates_path, :class => 'main' %>