config/routes.rb
ApprenticeDocLab1::Application.routes.draw do
  get "report_bot/unwritten"

  get "report_bot/unchecked"

  get "report_bot/show"

  resources :report_template_entries, :only => [ :edit, :update ]
  
  resources :users

  resources :print_reports, :only => [ :show ]

  resources :templates

  resources :statuses, :only => [ :create, :update, :destroy ]

  resources :sessions, :only => [ :new, :create, :destroy, :show ]

  resources :roles, :only => [ :index, :new, :edit, :create, :update, :destroy ]

  resources :reviews, :only => [ :create, :edit, :update, :destroy ]

  resources :reports, :only => [ :index, :show, :new, :edit, :create, :update, :destroy ] do
    resources :report_entries, :only => [ :new, :edit, :create, :update, :destroy ]
  end

  resources :passwords, :only => [ :new, :create, :show ]

  resources :jobs

  resources :ihks

  resources :codes

  resources :apprenticeships, :only => [ :index, :create, :destroy ]

  root :to => 'sessions#new'

  match '/welcome', :to => 'sessions#show'
  match '/signout', :to => 'sessions#destroy'
  
  

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :name
  has_many :templates
  validates :name, :presence => true
  validates :name, :length => { :in => 1..200}
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate
  before_filter :admin

  def index
    setupPager(Job, params)
    search = params[:search]
    if search.nil?
      @jobs = pager(Job).order('name').all
    else
      @jobs = pager(Job).where(['name LIKE ?', "%#{search}%"]).order('name')
    end
    @title = "Job Liste"
    respond_to do |format|
      format.html
    end
  end

  def show
    @job = Job.find(params[:id])
    @title = "Job Details"
    respond_to do |format|
      format.html
    end
  end

  def edit
    @job = Job.find(params[:id])
    @title = "Job bearbeiten"

    respond_to do |format|
      format.html
    end
  end

  def new
    @job = Job.new
    @title = "Job anlegen"

    respond_to do |format|
      format.html
    end
  end

  def create
    @job = Job.new(params[:job])
    
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Der Job wurde erfolgreich angelegt' }
      else
        format.html { render action: "new" }
      end
    end

  end

  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Der Job wurde erfolgreich bearbeitet' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<h1><%= title %></h1>
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> verhinderte, dass dieser Job gespeichert werden konnte: :</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :maxlength => 200, :size => 20 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<%= render 'form' %>

<%= link_to 'Details', @job, :class => 'main' %> |
<%= link_to 'Zurück', jobs_path, :class => 'main' %>

app/views/jobs/index.html.erb
<%= form_tag jobs_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Job finden", :name => nil %>
  </p>
<% end %>

<h1><%= title %></h1>

<% m = method(:jobs_path) %>
<%= pagerViewStart(m) %>
<%= pagerViewPrev(m) %>
<%= pagerViewNext(m) %>
<%= pagerViewEnd(m) %>

<table class="main">
<tr class="main">
<th class="main">Name</th>
</tr>

<% @jobs.each do |job| %>
<tr class="main">
<td class="main"><%= job.name %></td>
<td class="main"><%= link_to 'Details', job, :class => 'main' %></td>
<td class="main"><%= link_to 'Bearbeiten', edit_job_path(job), :class => 'main' %></td>
<td class="main"><%= link_to 'Löschen', job, :confirm => 'Sind Sie sicher?', :method => :delete, :class => 'main' %></td>
</tr>
<% end %>
</table>
<br />

<%= link_to 'Neuer Job', new_job_path, :class => 'main' %>

app/views/jobs/new.html.erb
<%= render 'form' %>

<%= link_to 'Zurück', jobs_path, :class => 'main' %>

app/views/jobs/show.html.erb
<h1><%= title %></h1>
<p>
  <b>Name:</b>
  <%= @job.name %>
</p>


<%= link_to 'Bearbeiten', edit_job_path(@job), :class => 'main' %> |
<%= link_to 'Zurück', jobs_path, :class => 'main' %>