config/routes.rb
ApprenticeDocLab1::Application.routes.draw do
  get "report_bot/unwritten"

  get "report_bot/unchecked"

  get "report_bot/show"

  resources :report_template_entries, :only => [ :edit, :update ]
  
  resources :users

  resources :print_reports, :only => [ :show ]

  resources :templates

  resources :statuses, :only => [ :create, :update, :destroy ]

  resources :sessions, :only => [ :new, :create, :destroy, :show ]

  resources :roles, :only => [ :index, :new, :edit, :create, :update, :destroy ]

  resources :reviews, :only => [ :create, :edit, :update, :destroy ]

  resources :reports, :only => [ :index, :show, :new, :edit, :create, :update, :destroy ] do
    resources :report_entries, :only => [ :new, :edit, :create, :update, :destroy ]
  end

  resources :passwords, :only => [ :new, :create, :show ]

  resources :jobs

  resources :ihks

  resources :codes

  resources :apprenticeships, :only => [ :index, :create, :destroy ]

  root :to => 'sessions#new'

  match '/welcome', :to => 'sessions#show'
  match '/signout', :to => 'sessions#destroy'
  
  

end

app/models/code.rb
class Code < ActiveRecord::Base
  attr_accessible :name, :code, :codegroup
  has_many :templates
  validates :code, :codegroup, :name, :presence => true
  validates :name, :length => { :in => 1..200}
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_filter :authenticate
  before_filter :admin
  
  def index
    setupPager(Code, params)
    search = params[:search]
    if search.nil?
      @codes = pager(Code).order('name').all
    else
      @codes = pager(Code).where(['name LIKE ?', "%#{search}%"]).order('name')
    end
    @title = "Schablonen-Liste"
    respond_to do |format|
      format.html
    end
  end

  def show
    @code = Code.find(params[:id])
    @title = "Schablonen-Details"
    respond_to do |format|
      format.html
    end
  end

  def edit
    @code = Code.find(params[:id])
    @title = "Schablone bearbeiten"

    respond_to do |format|
      format.html
    end
  end

  def new
    @code = Code.new
    @title = "Schablone anlegen"

    respond_to do |format|
      format.html
    end
  end

  def create
    @code = Code.new(params[:code])
    
    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: 'Der Code wurde erfolgreich angelegt' }
      else
        format.html { render action: "new" }
      end
    end

  end

  def update
    @code = Code.find(params[:id])

    respond_to do |format|
      if @code.update_attributes(params[:code])
        format.html { redirect_to @code, notice: 'Der Code wurde erfolgreich bearbeitet' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @code = Code.find(params[:id])
    @code.destroy

    respond_to do |format|
      format.html { redirect_to codes_url }
    end
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_form.html.erb
<%= form_for(@code) do |f| %>
  <% if @code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code.errors.count, "error") %> verhinderte, dass dieser Code gespeichert werden konnte: :</h2>

      <ul>
      <% @code.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h1><%= title %></h1>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :maxlength => 200, :size => 20 %>
  </div>
  
  <label for="code_codegroup">Einteilung</label> <br />
  <select id="code_codegroup_id" name="code[codegroup]">
    <option value=<%= PrintReportsHelper::HOURLY %> 
    <% if @code.codegroup == PrintReportsHelper::HOURLY %> 
      selected="selected" 
    <% end %>  
    >Stündlich</option>
    <option value=<%= PrintReportsHelper::DAILY %>
    <% if @code.codegroup == PrintReportsHelper::DAILY %> 
      selected="selected" 
    <% end %>  
    >Täglich</option>
    <option value=<%= PrintReportsHelper::WEEKLY %>
    <% if @code.codegroup == PrintReportsHelper::WEEKLY %> 
      selected="selected" 
    <% end %>  
    >Wöchentlich</option>
  </select>
  <br />
  
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_area :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/codes/edit.html.erb
<%= render 'form' %>

<%= link_to 'Details', @code, :class => 'main' %> |
<%= link_to 'Zurück', codes_path, :class => 'main' %>

app/views/codes/index.html.erb
<h1><%= title %></h1>

<%= form_tag codes_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Schablone finden", :name => nil %>
  </p>
<% end %>

<% m = method(:codes_path) %>
<%= pagerViewStart(m) %>
<%= pagerViewPrev(m) %>
<%= pagerViewNext(m) %>
<%= pagerViewEnd(m) %>

<table class="main">
<tr class="main">
<th class="main">Name</th>
<th class="main">Einteilung</th>
</tr>

<% @codes.each do |code| %>
<tr class="main">
<td class="main"><%= code.name %></td>

<td class="main">
<% if code.codegroup == PrintReportsHelper::HOURLY %> 
Stündlich
<% end %>
<% if code.codegroup == PrintReportsHelper::DAILY %> 
Täglich
<% end %>
<% if code.codegroup == PrintReportsHelper::WEEKLY %> 
Wöchentlich
<% end %>
</td>
<td class="main"><%= link_to 'Details', code, :class => 'main' %></td>
<td class="main"><%= link_to 'Bearbeiten', edit_code_path(code), :class => 'main' %></td>
<td class="main"><%= link_to 'Löschen', code, :confirm => 'Sind Sie sicher?', :method => :delete, :class => 'main' %></td>
</tr>
<% end %>
</table>
<br />

<%= link_to 'Neue Schablone', new_code_path, :class => 'main' %>

app/views/codes/new.html.erb
<%= render 'form' %>

<%= link_to 'Zurück', codes_path, :class => 'main' %>

app/views/codes/show.html.erb
<h1><%= title %></h1>
<p>
  <b>Name:</b><%= @code.name %><br />
  <b>Einteilung:</b>
<% if @code.codegroup == PrintReportsHelper::HOURLY %> 
Stündlich
<% end %>
<% if @code.codegroup == PrintReportsHelper::DAILY %> 
Täglich
<% end %>
<% if @code.codegroup == PrintReportsHelper::WEEKLY %> 
Wöchentlich
<% end %>
  <br/>
  <b>Schablone:</b><br />
  <%=raw @code.code %>
</p>


<%= link_to 'Bearbeiten', edit_code_path(@code), :class => 'main' %> |
<%= link_to 'Zurück', codes_path, :class => 'main' %>