config/routes.rb
ApprenticeDocLab1::Application.routes.draw do
  get "report_bot/unwritten"

  get "report_bot/unchecked"

  get "report_bot/show"

  resources :report_template_entries, :only => [ :edit, :update ]
  
  resources :users

  resources :print_reports, :only => [ :show ]

  resources :templates

  resources :statuses, :only => [ :create, :update, :destroy ]

  resources :sessions, :only => [ :new, :create, :destroy, :show ]

  resources :roles, :only => [ :index, :new, :edit, :create, :update, :destroy ]

  resources :reviews, :only => [ :create, :edit, :update, :destroy ]

  resources :reports, :only => [ :index, :show, :new, :edit, :create, :update, :destroy ] do
    resources :report_entries, :only => [ :new, :edit, :create, :update, :destroy ]
  end

  resources :passwords, :only => [ :new, :create, :show ]

  resources :jobs

  resources :ihks

  resources :codes

  resources :apprenticeships, :only => [ :index, :create, :destroy ]

  root :to => 'sessions#new'

  match '/welcome', :to => 'sessions#show'
  match '/signout', :to => 'sessions#destroy'
  
  

end

app/models/report.rb
# encoding: utf-8
#--
# Copyright (C) 2011, Dominik Cermak <d.cermak@arcor.de>
#
# This file is part of ApprenticeDocLab1, an application written for
# buschmais GbR <http://www.buschmais.de/>.
#
# ApprenticeDocLab1 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# ApprenticeDocLab1 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ApprenticeDocLab1.  If not, see <http://www.gnu.org/licenses/>.
#++

# == Bericht
#
# <b>Attribute:</b>
# * Anfangsdatum: period_start
# * Enddatum: period_end
#
# <b>Assoziationen (hat):</b>
# * beliebig viele Einträge: report_entries
# * einen Status : status
#
# <b>Assoziation (gehört zu):</b>
# * einem User : user
class Report < ActiveRecord::Base
  attr_accessible :period_start, :period_end, :reportnumber

  belongs_to :user
  has_many :report_entries, :dependent => :destroy
  has_one :status, :dependent => :destroy

  validates :period_start, :presence => true
  validates :period_end, :presence => true
  validates :user_id, :presence => true

  validate :period_end_after_period_start

  private
    def period_end_after_period_start
      if period_start and period_end
        errors[:base] << 'Bis: muss nach Von: liegen.' if period_end < period_start
      end
    end
end

app/controllers/reports_controller.rb
# encoding: utf-8
#--
# Copyright (C) 2011, Dominik Cermak <d.cermak@arcor.de>
#
# This file is part of ApprenticeDocLab1, an application written for
# buschmais GbR <http://www.buschmais.de/>.
#
# ApprenticeDocLab1 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# ApprenticeDocLab1 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ApprenticeDocLab1.  If not, see <http://www.gnu.org/licenses/>.
#++

# Ist für die Interaktion mit den Berichten zuständig.
#
# Nur eingeloggte Benutzer können seine Funktionalität nutzen,
# des weiteren benötigen sie das Lesen-Recht (read) für #index und #show
# und das Freigeben-Recht (commit) für #new, #create, #update, #destroy.
# #edit, #update und #destroy darf nur vom Autor ausgeführt werden.
# #show erfordert entweder den Autor, oder einen freigegebenen Bericht und einen Ausbilder.
# Berichte die freigegeben oder bereits akzeptiert wurden, können nicht mehr bearbeitet werden.
# Hat ein Benutzer Ausbildungsbeginn oder Ausbildungsjahr nicht gesetzt, so kann er keine
# Berichte anlegen, bzw. bearbeiten.
class ReportsController < ApplicationController
	
  before_filter :authenticate
  before_filter :read, :only => [ :index, :show ]
  before_filter :correct_user_or_instructor, :only => :show
  before_filter :commit, :only => [ :new, :create, :update, :destroy ]
  before_filter :not_commited, :only => [ :edit, :update, :destroy ]
  before_filter :not_accepted, :only => [ :edit, :update ]
  before_filter :correct_user, :only => [ :edit, :update, :destroy, :show ]
  before_filter :trainingbegin_and_year_set, :only => [ :create, :update ]

  # Listet Berichte auf. Welche Bericht angezeigt werden hängt von den Rechten des
  # Benutzers ab:
  # * Freigeben (commit): alle Berichte des Benutzers
  # * Prüfen (check): alle Berichte der dem Benutzer zugewiesenen Azubis oder alle freigegebenen Berichte aller Azubis wenn der Parameter all == true
  def index
    setupPager(current_user.reports,params)
    if current_user.role.commit?
      @reports = pager(current_user.reports).order('period_start asc, period_end asc')
    elsif current_user.role.check?
      if params[:all]
        @reports = Report.joins(:status).where(:statuses => { :stype => Status.commited }).order('period_start asc, period_end asc')
      else
        @reports = Report.joins(:status, :user).where(:statuses => { :stype => Status.commited }, :user_id => current_user.apprentices).order('period_start asc, period_end asc')
      end
    end

    respond_to do |format|
       format.html
       format.json { render json: @reports }
    end

  end

  # Zeigt die Einträge eines Berichts.
  def show
    @report = Report.find(params[:id])
    @entries = @report.report_entries.order('date asc')
    
    respond_to do |format|
       format.html
       format.json { render json: @entries, except: [:duration_in_hours] }
    end
  end

  # Zeigt das Formular zum Erstellen eines neuen Berichts.
  def new
    @report = Report.new
    # Setze die Werte, mit denen die Felder vorausgefüllt werden.
    @date = Date.today.beginning_of_day

    if not current_user.template.nil?
      codegroup = current_user.template.code.codegroup
      if codegroup == PrintReportsHelper::DAILY
        @date = @date.beginning_of_week
      elsif codegroup == PrintReportsHelper::WEEKLY
        @date = @date.beginning_of_month.beginning_of_week
      end
    end

    @report.period_start = @date
    
    respond_to do |format|
       format.html
       format.json { render json: @report }
    end
  end

  # Zeigt das Formular zum Bearbeiten eines vorhandenen Berichts.
  def edit
    @report = Report.find(params[:id])
    
    respond_to do |format|
       format.html
       format.json { render json: @report }
    end
    
  end

  # Legt einen neuen Bericht, sowie dessen initialen Status an und leitet auf #index weiter.
  # Ist der Bericht nicht valid, so wird das Formular erneut gezeigt.
  def create
    @report = current_user.reports.build(params[:report])
    #@report = reports.build(params[:report])
    # Jeder Bericht muss einen Status haben, also erstelle ihn zusammen mit dem Bericht.
    @report.build_status(:stype => Status.personal)
    @report.reportnumber = current_user.reports.count + 1
    if !@report.period_start.nil?
      @report.period_end = calc_period_end(@report.period_start)

      if no_time_overlap(@report,@report,false) && period_valid(@report,@report)
        if @report.save
          respond_to do |format|
            format.html { redirect_to reports_path, notice: 'Bericht wurde erfolgreich erstellt.' }
            format.json { render json: @report }
          end
          return
        end
      end
    end
    respond_to do |format|
      format.html { render 'new' }
      format.json { render json: { error: @report.errors }, status: :unprocessable_entity }
    end
  end

  # Ändert die Attribute des Berichts und leitet auf #index weiter.
  # sind die Attribute nicht valid, so wird das Formular erneut gezeigt.
  def update
    @report = Report.find(params[:id])
    
    # Hilfsobjekt für den Vergleich der Daten.
    @new = Report.new(params[:report])

    if @new.period_start != nil
      @new.period_end = calc_period_end(@new.period_start)
      @shift = (@new.period_start - @report.period_start)

      if no_time_overlap(@new,@report,true) && period_valid(@new,@report)
        if params[:report] != nil && @report.update_attributes(params[:report].merge(:period_end => @new.period_end))
          @report.report_entries.each { |e| e.update_attribute(:date, (e.date + @shift.days)) }
          # Der Status des Berichts wird durch das Bearbeiten wieder auf personal gesetzt, damit er wieder
          # freigegeben werden kann.
          @report.status.update_attributes(:stype => Status.personal)
          respond_to do |format|
            format.html { redirect_to reports_path, notice: 'Bericht wurde erfolgreich erstellt.' }
            format.json { render json: @report }
          end
          return
        end
      end
    end
    respond_to do |format|
      format.html { render :edit }
      format.json { render json: { error: @report.errors }, status: :unprocessable_entity }
    end
  end

  # Löscht einen Bericht aus dem System und leitet auf #index weiter.
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_path, :notice => 'Bericht wurde erfolgreich gelöscht.' }
      format.json { render nothing: true, status: :ok }
    end
  end

  private
    # Leitet den Benutzer auf die Willkommen-Seite, falls er nicht der Besitzer des Berichts ist.
    def correct_user
      user = Report.find(params[:id]).user
      redirect_to welcome_path unless current_user?(user)
    end

    # Leitet den Benutzer auf die Willkommen-Seite, außer er ist der Autor des Berichts oder der Bericht ist freigegeben und der Benutzer
    # ist ein Ausbilder.
    def correct_user_or_instructor
      report = Report.find(params[:id])
      redirect_to welcome_path, :alert => 'Sie haben nicht die Berechtigung diesen Bericht anzuzeigen.' unless current_user?(report.user) || (report.status.stype == Status.commited && current_user.role.check?)
    end

    # Leitet den Benutzer auf die Berichtsübersicht-Seite, wenn der Bericht akzeptiert ist.
    def not_accepted
      report = Report.find(params[:id])
      redirect_to reports_path, :alert => 'Da der Bericht schon akzeptiert wurde, sind Änderungen nicht mehr möglich.' if report.status.stype == Status.accepted
    end

    # Leitet den Benutzer auf die Berichtsübersicht-Seite, wenn der Bericht freigegeben ist.
    def not_commited
      report = Report.find(params[:id])
      redirect_to reports_path, :alert => 'Da der Bericht freigegeben wurde, sind Änderungen nicht mehr möglich.' if report.status.stype == Status.commited
    end

    # Leitet den Benutzer auf die Berichtsübersicht-Seite, wenn kein Ausbildungsbeginn oder Ausbildungsjahr gesetzt ist.
    def trainingbegin_and_year_set
      redirect_to reports_path, :alert => 'Um diese Aktion durchführen zu können müssen sowohl Ausbildungsbeginn als auch Ausbildungsjahr gesetzt sein.' if current_user.trainingbegin.nil? or current_user.trainingyear.nil?
    end

    # Validiert, dass es keine zeitlichen Überschneidungen zwischen Berichten gibt.
    def no_time_overlap(report,error_report,update)
      if report.period_start and report.period_end
        reports = current_user.reports.where("(period_start <= :period_start AND period_end >= :period_start) OR
                                             (period_start <= :period_end AND period_end >= :period_end) OR
                                             (period_start >= :period_start AND period_end <= :period_end )",
                                             :period_start => report.period_start,
                                             :period_end => report.period_end)
        if reports.length > 0
          if update && reports.length == 1 && reports.first.id == error_report.id
            return true
          end
          error_report.errors[:base] << 'Es darf keine zeitlichen Überlappungen mit anderen Berichten geben.'
          return false
        else
          return true
        end
      end
      return false
    end

    # Validiert, dass der Zeitraum im Bereich Ausbildungsbeginn bis Ausbildungsbeginn + Ausbildungsjahr liegt
    def period_valid(report,error_report)

app/views/reports/_form.html.erb
<%= form_for @report do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.template.header', :model=> 'Bericht', :count=> @report.errors.count) %></h2>
      <h2><%= t('errors.template.body') %></h2>
      <ul>
        <% @report.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label "Berichtsanfang:" %><br />
  <%= f.date_select :period_start %><br />
  <%= @report.new_record? ? f.submit('Bericht anlegen') : f.submit('Änderungen speichern') %>
<% end %>

app/views/reports/edit.html.erb
<h1>Bericht bearbeiten</h1>

<%= render 'form' %>

<br />

<%= link_to 'Zurück', reports_path, :class => 'main' %>

app/views/reports/index.html.erb
<h1>Berichte-Übersicht</h1>

<% m = method(:reports_path) %>
<%= pagerViewStart(m) %>
<%= pagerViewPrev(m) %>
<%= pagerViewNext(m) %>
<%= pagerViewEnd(m) %>

<table class="main">
  <tr class="main">
    <th class="main">Vom</th>
    <th class="main">Bis</th>
    <% if current_user.role.check? %>
      <th class="main">Azubi</th>
    <% end %>
    <th class="main">Status</th>
  </tr>
  <% @reports.each do |report| %>
    <tr class="main">
      <td class="main"><%= l report.period_start %></td>
      <td class="main"><%= l report.period_end %></td>
      <% if current_user.role.check? %>
        <td class="main"><%= report.user.forename + ' ' + report.user.name %></td>
      <% end %>
      <td class="main"><%= report.status.name %></td>
      <% if current_user.role.commit? && (report.status.stype == Status.personal || report.status.stype == Status.rejected) %>
        <td class="main"><%= link_to 'Einträge bearbeiten', edit_report_template_entry_path(report), :class => 'main' %></td>
        <td class="main"><%= link_to 'Bearbeiten', edit_report_path(report), :class => 'main' %></td>
        <td class="main"><%= link_to 'Löschen', report_path(report), :confirm => "Sind Sie sicher?", :method => :delete, :class => 'main' %></td>
      <% else %>
        <td class="main" colspan="3" />
      <% end %>
      <% if current_user.role.commit? %>
        <% if report.status.stype == Status.personal && !report.report_entries.blank? %>
          <td class="main"><%= link_to 'Bericht vorlegen', reviews_path(:report_id => report), :method => :post, :class => 'main' %></td>
        <% elsif report.status.stype == Status.commited %>
          <td class="main"><%= link_to 'Bericht zurückziehen', review_path(report), :method => :delete, :class => 'main' %></td>
        <% else %>
          <td class="main" />
        <% end %>
      <% elsif current_user.role.check? %>
        <td class="main"><%= link_to 'Anzeigen', report, :class => 'main' %></td>
      <% end %>
      <% if report.status.stype == Status.accepted && current_user.role.export? %>
        <td class="main"><%= link_to 'Druckansicht', print_report_path(report), :class => 'main' %></td>
      <% else %>
        <td class="main" />
      <% end %>
    </tr>
  <% end %>
</table>

<% if current_user.role.commit? %>
  <%= link_to 'Bericht anlegen', new_report_path, :class => 'main' %>
<% end %>
<% if current_user.role.check? %>
  <%= link_to 'Alle freigegebenen Berichte', reports_path(:all => true), :class => 'main' %>
<% end %>

app/views/reports/new.html.erb
<h1>Bericht anlegen</h1>

<%= render 'form' %>

<br />

<%= link_to 'Zurück', reports_path, :class => 'main'%>

app/views/reports/show.html.erb
<h1>Bericht vom <%= l @report.period_start %> bis zum <%= l @report.period_end %></h1>

<% if current_user.role.commit? %>
  <% if @report.status.stype == Status.personal && !@report.report_entries.blank? %>
    <%= link_to 'Bericht vorlegen', reviews_path(:report_id => @report), :method => :post, :class => 'main' %>
  <% elsif @report.status.stype == Status.commited %>
    <%= link_to 'Bericht zurückziehen', review_path(@report), :method => :delete, :class => 'main' %>
  <% end %>
<% elsif current_user.role.check? %>
  <% if @report.status.stype == Status.commited %>
    <%= link_to 'Bericht akzeptieren', review_path(@report), :method => :delete, :class => 'main' %>
    |
    <%= link_to 'Bericht ablehnen', edit_review_path(@report), :class => 'main' %>
  <% end %>
<% end %>

<% if @report.status.comment? %>
  <p><strong>Kommentar des Ausbilders:</strong> <%= @report.status.comment%></p>
<% end %>

<table class="main">
  <tr class="main">
    <th class="main">Datum/Uhrzeit</th>
    <th class="main">Text</th>
  </tr>
  <% @entries.each do |entry| %>
    <tr class="main">
      <td class="main center"><%= l entry.date, :format => "%d. %B" %></td>
      <% entry.duration_in_hours = 0 unless not entry.duration_in_hours.nil? %>
      <td class="main"><%= entry.text %></td>
      <% if current_user.role.commit? %>
        <td class="main"><%= link_to 'Löschen', report_report_entry_path(@report, entry), :confirm => "Sind Sie sicher?", :method => :delete, :class => 'main' %></td>
      <% end %>
    </tr>
  <% end %>
</table>